#BlackJack Pro settings
#Sat Jun 27 17:54:35 PDT 2026
aiPersonality=cautious
dealerHitsSoft17=false
lateSurrender=true
musicEnabled=true
musicVolume=0.4
offerInsurance=true
sfxEnabled=true
sfxVolume=0.6
themeId=classic
